Repository team-xquare/v1-service-user, pull requests merged in 2023-05, with the labels that each got.

#120 🔀 :: (#31) codeowners 수정
  .github/CODEOWNERS
Labels: chore

#122 🔀 :: (#41) permitAll 수정
  user-infrastructure/src/main/kotlin/com/xquare/v1userservice/configuration/security/SecurityConfig.kt
Labels: chore

#125 🔀 :: (#48) 제외된 유저 목록 조회
  user-domain/src/main/kotlin/com/xquare/v1userservice/stubs/InMemoryUserRepository.kt
  user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/UserApi.kt
  user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/dtos/ExcludeUserIdListResponse.kt
  user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/UserApiImpl.kt
  user-domain/src/main/kotlin/com/xquare/v1userservice/user/spi/UserRepositorySpi.kt
  user-infrastructure/src/main/kotlin/com/xquare/v1userservice/configuration/security/SecurityConfig.kt
  user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/repository/UserRepositoryImpl.kt
  user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt
  user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserRouter.kt
Labels: 기능 추가

#127 🔀 :: (#73) Exclude User List Null 처리
  user-domain/src/main/kotlin/com/xquare/v1userservice/stubs/InMemoryUserRepository.kt
  user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/UserApi.kt
  user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/UserApiImpl.kt
  user-domain/src/main/kotlin/com/xquare/v1userservice/user/spi/UserRepositorySpi.kt
  user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/repository/UserRepositoryImpl.kt
  user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt
Labels: 버그

#129 🔀 :: (#85) ExcludeUserList Params extension util
  user-infrastructure/src/main/kotlin/com/xquare/v1userservice/configuration/extension/Util.kt
  user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt
Labels: 리팩토링

#128 🔀 :: (#36) 권한 설정 문제 해결
  user-infrastructure/src/main/kotlin/com/xquare/v1userservice/configuration/security/SecurityConfig.kt
  user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/aop/RequestHeaderAspect.kt
  user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/exceptions/InvalidSecretValueException.kt
  user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt
Labels: chore

#130 🔀 :: (#81) 4096 bytes Error 해결
  user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt
  user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/dto/GetExcludeUserIdListRequest.kt
Labels: 버그

#133 🔀 :: (#97) CODEOWNERS 수정
  .github/CODEOWNERS
Labels: chore

#132 🔀 :: (#95) 선생님 정보 조회 API 이름순 정렬 추가
  user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/repository/UserRepositoryImpl.kt
Labels: chore

#135 🔀 :: (#134) RefreshToken 만료 시간 수정
  user-infrastructure/src/main/kotlin/com/xquare/v1userservice/jwt/JwtToken.kt
  user-infrastructure/src/main/kotlin/com/xquare/v1userservice/jwt/JwtTokenGenerator.kt
  user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/spi/JwtTokenGeneratorSpiImpl.kt
Labels: 리팩토링
